name: Release Higgs Shop

on:
    workflow_dispatch:
        inputs:
            dryRun:
                description: 'Do a dry run to preview instead of a real release [true/false]'
                required: true
                default: 'true'

defaults:
      run:
        working-directory: core-sdk-samples/higgs-shop-sample-app

jobs:
    confirm-main-branch:
        name: Confirm release is run on public/main branch
        runs-on: macOS-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Branch name
              run: |
                  BRANCHNAME=${GITHUB_REF##*/}
                  echo "confirming branch name, branch name is:"
                  echo $BRANCHNAME
                  if [ $BRANCHNAME != "main" ]
                  then
                    echo "You can only run a release from the main branch, you are trying to run it from ${BRANCHNAME}"
                    exit 1
                  fi

    fetch-data-plans:
        name: "Fetch Data Plan"
        runs-on: ubuntu-latest
        needs: confirm-main-branch
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Use Node.js
            uses: actions/setup-node@v1
            with:
              node-version: '16.x'

          - name: Install mP CLI
            run: npm install -g @mparticle/cli

          - name: Fetch Data Plans with mp CLI
            id: fetch-data-plans
            env:
              WORKSPACE_ID: ${{ secrets.HIGGS_SHOP_WORKSPACE_ID }}
              CLIENT_ID: ${{ secrets.HIGGS_SHOP_CLIENT_ID }}
              CLIENT_SECRET: ${{ secrets.HIGGS_SHOP_CLIENT_SECRET }}
            run: |
              mp planning:data-plan-versions:fetch --dataPlanId=higgs_shop_basic_data_plan --versionNumber=1 --outFile=dataplans/higgs_shop_basic_data_plan_1.json --workspaceId=$WORKSPACE_ID --clientId=$CLIENT_ID --clientSecret=$CLIENT_SECRET
          
          - name: Archive Data Plan Artifacts
            uses: actions/upload-artifact@v3
            with:
              name: higgs-shop-dataplan
              path: core-sdk-samples/higgs-shop-sample-app/dataplans/

          - name: Commit Data Plans to Git
            uses: EndBug/add-and-commit@v9
            with:
              message: Update Higgs Shop Data Plan
              add: core-sdk-samples/higgs-shop-sample-app/dataplans
              author_name: mparticle-bot
              author_email: developers@mparticle.com
              committer_name: mparticle-bot
              committer_email: developers@mparticle.com

    release:
        name: Perform Release
        runs-on: macOS-latest
        needs: confirm-main-branch
        env:
            GIT_AUTHOR_NAME: mparticle-bot
            GIT_AUTHOR_EMAIL: developers@mparticle.com
            GIT_COMMITTER_NAME: mparticle-bot
            GIT_COMMITTER_EMAIL: developers@mparticle.com

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Release --dry-run
              if: ${{ github.event.inputs.dryRun == 'true'}}
              env:
                  GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
              run: |
                npx \
                -p lodash \
                -p semantic-release@17 \
                -p @semantic-release/changelog@5 \
                -p @semantic-release/git@9 \
                -p @semantic-release/exec@5 \
                semantic-release \
                --dry-run --branches main

            - name: Release
              if: ${{ github.event.inputs.dryRun == 'false'}}
              env:
                  GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
              run: |
                npx \
                -p lodash \
                -p semantic-release@17 \
                -p @semantic-release/changelog@5 \
                -p @semantic-release/git@9 \
                -p @semantic-release/exec@5 \
                semantic-release \
                --branches main
